### ISSUE TITLE
tarfile.ReadError

### ISSUE THREAD

**Issue by rflameiro** [josejimenezluna/delfta#76]
I have installed delfta with `conda install delfta -c delfta -c pytorch -c rusty1s -c conda-forge` on a WSL Ubuntu 20.04
Now I'm trying to execute the "First Run" commands, but both 
`python -c "import runpy; _ = runpy.run_module('delfta.download', run_name='__main__')"` and 
```
from delfta.download import _download_required
_download_required()
```

throw `tarfile.ReadError: file could not be opened successfully`
The file in question is under home/user/miniconda3/envs/delfta/lib/python3.8/tarfile.py

**Comment by josejimenezluna** [comment]
@cisert could you check that the download links are still up? libdrive has changed links for another project of mine

**Comment by josejimenezluna** [comment]
Hi @rflameiro, the download server was undergoing some maintenance yesterday. I tried to run the "first run" commands this morning with no issues.

Let us know if you're still encountering problems.

**Comment by rflameiro** [comment]
Thank you for the prompt reply! I must inform you that the "runpy" command is still showing the same error to me (I even created a new env to check), but the second way worked fine, and I was able to use delfta.
