### ISSUE TITLE
E_gap doesn't always equal E_lumo - E_homo

### ISSUE THREAD

**Issue by varys50** [josejimenezluna/delfta#83]
While I realize E_gap is a separate model itself, the value it returns is sometimes way different from calculating E_lumo - E_homo.  For example, take the following molecule with the following settings:

```
calc = DelftaCalculator(delta=True, xtbopt=True, return_optmols=True, addh=True)
mol = readstring("smi", "C[C@@H]1CC[C@@H]2C(C)(C)[C@H](O)[C@]3(C)CC[C@@]21C3")

```
Results are:

'E_homo': -0.23676376
'E_lumo': 0.11727003
'E_gap': 0.12012529

E_gap should be close to 0.354

**Comment by josejimenezluna** [comment]
Hi @varys50, thanks for taking an interest in this project!

We never conducted any analyses on whether the gap model was actually more accurate than the difference between the homo and lumo ones. Please feel free to conduct those yourself on the delfta test set if this issue bothers you. 

However, this does not feel like an issue relevant to taking any action in regards to the repository and hence I'm closing.
