### ISSUE TITLE
Using QMugs as a Pytorch Geometric dataset

### ISSUE THREAD

**Issue by arunraja-hub** [josejimenezluna/delfta#84]
Hi, I would like to use the QMugs dataset used in this work with PyTorch Geometric. I am trying to set it up as an InMemoryDataset similar to how QM9 has been setup in PyG: https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/qm9.html#QM9

Could you please guide on converting QMugs to a PyG dataset? for eg., which urls should I use for `raw_url` and `raw_dir `?

**Comment by josejimenezluna** [comment]
Hi @arunraja-hub, you may want to have a look at how the H5 file is downloaded for training. 

Here is where we pull the dataset from: https://github.com/josejimenezluna/delfta/blob/master/delfta/download.py#L17

If you want to have access to the actual raw DFT files please have a look at the files made available through the ETH Research collection: https://www.research-collection.ethz.ch/handle/20.500.11850/482129
